### ISSUE TITLE
Problem: layout issue for development-and-analysis and hyperflow

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide-website-styx#137]
### step to reproduce
* navigate to fractalide.com using a *desktop*

### Actual behaviour
* Hyperflow
![hyperflow-layout-issue](https://user-images.githubusercontent.com/158321/40282360-c3efd260-5ca0-11e8-8dba-f4d40b586fc5.png)
* Development and services
![layout-broken-development-analysis](https://user-images.githubusercontent.com/158321/40282361-c82e7f66-5ca0-11e8-9aee-135a8965ee57.png)
* Cardano Stake Pool
![cardano-stake-pool](https://user-images.githubusercontent.com/158321/40282446-006f6092-5ca2-11e8-9c26-b435c079378c.png)

### Expected behaviour
Should be side-by-side

**Comment by sjmackenzie** [comment]
btw the cardano-stake-pool also has an issue (I updated the issue probably after you closed it)

**Comment by dapyh17d4** [comment]
**step to reproduce**
Navigate to http://fractalide.com/hyperflow/ using a desktop

**Actual behaviour**
<img width="1440" alt="screen shot 2018-05-22 at 10 24 38 am" src="https://user-images.githubusercontent.com/39090829/40338977-b4295f62-5daa-11e8-9ced-a218157f8ebe.png">

**Expected behaviour**
To have the same amount of space between the images
