### ISSUE TITLE
Problem: chinese font looks ugly

### ISSUE THREAD

**Issue by sjmackenzie** [fractalide/fractalide-website-styx#6]
Is there a way to change the chinese font without affecting the english font?

**Comment by sjmackenzie** [comment]
I'll get the name of the Chinese font to use is a moment

**Comment by sjmackenzie** [comment]
I think this one... https://cooltext.com/Download-Font-%E7%B4%B0%E6%98%8E%E9%AB%94+MingLiU

**Comment by ericsagnes** [comment]
The problem with CJK fonts is that they are very heavy due to the large number of characters, the one linked is about 26 MB and that is not very nice for smartphones or devices with bandwidth restrictions.

I don't use any chinese device, but I guess a Chinese user __should__ have chinese fonts already installed on his device and picked by default.

Does other chineses web pages also have ugly fonts or is this just on this site?
Check on this [page](https://zh.wikipedia.org/wiki/%E6%B0%B4) for example.

**Comment by sjmackenzie** [comment]
Ah yes, you're right, from a computer that has nice fonts it renders quite nicely. Lets drop this issue!
